# Default upstreams (will be overwritten by deploy.sh)
upstream frontend_backend {
    server prepodavai-frontend-blue-prod:3000;
}

upstream api_backend {
    server prepodavai-backend-blue-prod:3001;
}
