import { apiClient } from '@/lib/api/client'

export async function downloadPdf(html: string, filename = 'document.pdf', options?: { isWysiwyg?: boolean }): Promise<void> {
    // Do not run DOMPurify — it strips <script> tags including MathJax CDN.
    // The HTML is trusted content generated by the app or the AI, and the
    // PDF is rendered server-side in an isolated Playwright browser (no XSS risk).
    const fullHtml = /<\/head>/i.test(html)
        ? html
        : `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body>${html}</body></html>`

    const response = await apiClient.post('/generate/export-pdf', {
        html: fullHtml,
        isWysiwyg: options?.isWysiwyg
    }, { responseType: 'blob' })

    const url = URL.createObjectURL(response.data)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
}
